# Uncomment the commented lines to deploy a non "default" service with basic scaling
#service: backend
runtime: python311

#instance_class: B2
#basic_scaling:
#  max_instances: 1
#  idle_timeout: 5m

env_variables:
  FOOBAR: "baz"

handlers:
- url: /.*
  secure: always
  script: auto
  redirect_http_response_code: 301
